// lex.yy.cpp generated by reflex 6.1.0 from sql_lexer.l

#define REFLEX_VERSION "6.1.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_flex                true
#define REFLEX_OPTION_lex                 yylex
#define REFLEX_OPTION_lexer               yyFlexLexer
#define REFLEX_OPTION_noyywrap            true
#define REFLEX_OPTION_outfile             "lex.yy.cpp"
#define REFLEX_OPTION_prefix              yy
#define REFLEX_OPTION_reentrant           true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  FLEX-COMPATIBLE DEFINITIONS                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define INITIAL (0)
#define YY_NUM_RULES (51)

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  FLEX-COMPATIBLE ABSTRACT LEXER CLASS                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/flexlexer.h>
typedef reflex::FlexLexer<reflex::Matcher> FlexLexer;

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

class yyFlexLexer : public FlexLexer {
 public:
  yyFlexLexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, NULL means std::cout by default
      std::ostream *os = NULL)
    :
      FlexLexer(input, os)
  {
  }
  // the flex lexer function defined by SECTION 2
  virtual int yylex(void);
  // lexer functions accepting new input to scan
  int yylex(const reflex::Input& input)
  {
    in(input);
    return yylex();
  }
  int yylex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return yylex();
  }
};

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %{ user code %}                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 2 "sql_lexer.l"


#include "sql/parser/grammar/sql_grammar.h"
#include "sql/parser/token.h"
#include "sql/parser/parser.h"

#include <string.h>

namespace {

static void* g_parser = nullptr;
static lsql::sql::parse::Context* g_parse_context = nullptr;

} // namespace



////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REENTRANT                                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

typedef void *yyscan_t;
typedef yyFlexLexer yyscanner_t;

#ifndef YY_EXTERN_C
#define YY_EXTERN_C
#endif

YY_EXTERN_C int yylex(yyscan_t scanner)
{
  return static_cast<yyscanner_t*>(scanner)->yylex();
}

YY_EXTERN_C void yylex_init(yyscan_t *scanner)
{
  *scanner = static_cast<yyscan_t>(new yyscanner_t);
}

YY_EXTERN_C void yylex_init_extra(void* extra, yyscan_t *scanner)
{
  *scanner = static_cast<yyscan_t>(new yyscanner_t);
  yyset_extra(extra, *scanner);
}

YY_EXTERN_C void yylex_destroy(yyscan_t scanner)
{
  delete static_cast<yyscanner_t*>(scanner);
}

#undef yyget_text
YY_EXTERN_C char *yyget_text(yyscan_t scanner)
{
  return const_cast<char*>(static_cast<yyscanner_t*>(scanner)->text());
}

#undef yyget_leng
YY_EXTERN_C yy_size_t yyget_leng(yyscan_t scanner)
{
  return static_cast<yyscanner_t*>(scanner)->size();
}

#undef yyget_lineno
YY_EXTERN_C int yyget_lineno(yyscan_t scanner)
{
  return static_cast<yyscanner_t*>(scanner)->lineno();
}

#undef yyset_lineno
YY_EXTERN_C void yyset_lineno(int n, yyscan_t scanner)
{
  static_cast<yyscanner_t*>(scanner)->lineno(n);
}

#undef yyget_in
YY_EXTERN_C FILE *yyget_in(yyscan_t scanner)
{
  return static_cast<yyscanner_t*>(scanner)->in().file();
}

#undef yyset_in
YY_EXTERN_C void yyset_in(FILE *i, yyscan_t scanner)
{
  static_cast<yyscanner_t*>(scanner)->in(i);
}

#undef yyget_debug
YY_EXTERN_C int yyget_debug(yyscan_t scanner)
{
  return static_cast<yyscanner_t*>(scanner)->debug();
}

#undef yyset_debug
YY_EXTERN_C void yyset_debug(int f, yyscan_t scanner)
{
  static_cast<yyscanner_t*>(scanner)->set_debug(f);
}

#undef yyget_extra
YY_EXTERN_C void* yyget_extra(yyscan_t scanner)
{
  return static_cast<yyscanner_t*>(scanner)->yyextra;
}

#undef yyset_extra
YY_EXTERN_C void yyset_extra(void* x, yyscan_t scanner)
{
  static_cast<yyscanner_t*>(scanner)->yyextra = x;
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int yyFlexLexer::yylex(void)
{
  static const char *REGEX_INITIAL = "(?m)((?:[\\x09\\x0a\\x20]+))|((?:\\Q--\\E).*)|(SELECT)|(FROM)|(AS)|(WHERE)|(LIMIT)|(AND)|(OR)|(LIKE)|(MATERIALIZE)|(String)|(Int)|(Float)|(Bool)|(COUNT)|(true)|(false)|(null)|(ASC)|(DESC)|(MIN)|(MAX)|(SUM)|(IN)|(PERCENTILE)|(COALESCE)|(RSUBSTR)|((?:\\QGROUP BY\\E))|((?:\\QORDER BY\\E))|((?:\\QUNION ALL\\E))|((?:[0-9]+))|((?:[\\x2b\\x2d]?[0-9]+\\.[0-9]+))|((?:[A-Z_a-z][0-9A-Z_a-z]*))|((?:[/\\x5c]?(?:[\\x2d.0-9A-Z_a-z]+[/\\x5c]+)*[\\x2d.0-9A-Z_a-z]+))|((?:'[^']*'))|((?:[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}))|((?:\\Q;\\E))|((?:\\Q,\\E))|((?:\\Q*\\E))|((?:\\Q=\\E))|((?:\\Q!=\\E))|((?:\\Q(\\E))|((?:\\Q)\\E))|((?:\\Q!\\E))|((?:\\Q+\\E))|((?:\\Q/\\E))|((?:\\Q@\\E))|((?:\\Q$\\E))|(.)";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
    YY_USER_INIT
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
#line 268 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_EOF, NULL, 0};
                     Parse(g_parser, TOKEN_EOF, t, g_parse_context);
                     yyterminate();
                 }

            }
            else
            {
              output(matcher().input());
            }
            YY_BREAK
          case 1: // rule sql_lexer.l:29: {WHITESPACE} :
            YY_USER_ACTION
#line 29 "sql_lexer.l"
{ /* ignore */ }

            YY_BREAK
          case 2: // rule sql_lexer.l:31: "--".* :
            YY_USER_ACTION
#line 31 "sql_lexer.l"
{ /* ignore */  }

            YY_BREAK
          case 3: // rule sql_lexer.l:33: SELECT :
            YY_USER_ACTION
#line 33 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_SELECT, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_SELECT, t, g_parse_context);
                 }

            YY_BREAK
          case 4: // rule sql_lexer.l:38: FROM :
            YY_USER_ACTION
#line 38 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_FROM, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_FROM, t, g_parse_context);
                 }

            YY_BREAK
          case 5: // rule sql_lexer.l:43: AS :
            YY_USER_ACTION
#line 43 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_AS, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_AS, t, g_parse_context);
                 }

            YY_BREAK
          case 6: // rule sql_lexer.l:48: WHERE :
            YY_USER_ACTION
#line 48 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_WHERE, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_WHERE, t, g_parse_context);
                 }

            YY_BREAK
          case 7: // rule sql_lexer.l:53: LIMIT :
            YY_USER_ACTION
#line 53 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_LIMIT, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_LIMIT, t, g_parse_context);
                 }

            YY_BREAK
          case 8: // rule sql_lexer.l:58: AND :
            YY_USER_ACTION
#line 58 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_AND, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_AND, t, g_parse_context);
                 }

            YY_BREAK
          case 9: // rule sql_lexer.l:63: OR :
            YY_USER_ACTION
#line 63 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_OR, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_OR, t, g_parse_context);
                 }

            YY_BREAK
          case 10: // rule sql_lexer.l:68: LIKE :
            YY_USER_ACTION
#line 68 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_LIKE, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_LIKE, t, g_parse_context);
                 }

            YY_BREAK
          case 11: // rule sql_lexer.l:73: MATERIALIZE :
            YY_USER_ACTION
#line 73 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_MATERIALIZE, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_MATERIALIZE, t, g_parse_context);
                 }

            YY_BREAK
          case 12: // rule sql_lexer.l:78: String :
            YY_USER_ACTION
#line 78 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_STRING, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_STRING, t, g_parse_context);
                 }

            YY_BREAK
          case 13: // rule sql_lexer.l:83: Int :
            YY_USER_ACTION
#line 83 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_INT, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_INT, t, g_parse_context);
                 }

            YY_BREAK
          case 14: // rule sql_lexer.l:88: Float :
            YY_USER_ACTION
#line 88 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_FLOAT, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_FLOAT, t, g_parse_context);
                 }

            YY_BREAK
          case 15: // rule sql_lexer.l:93: Bool :
            YY_USER_ACTION
#line 93 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_BOOL, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_BOOL, t, g_parse_context);
                 }

            YY_BREAK
          case 16: // rule sql_lexer.l:98: COUNT :
            YY_USER_ACTION
#line 98 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_COUNT, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_COUNT, t, g_parse_context);
                 }

            YY_BREAK
          case 17: // rule sql_lexer.l:103: true :
            YY_USER_ACTION
#line 103 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_TRUE, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_TRUE, t, g_parse_context);
                 }

            YY_BREAK
          case 18: // rule sql_lexer.l:108: false :
            YY_USER_ACTION
#line 108 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_FALSE, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_FALSE, t, g_parse_context);
                 }

            YY_BREAK
          case 19: // rule sql_lexer.l:113: null :
            YY_USER_ACTION
#line 113 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_NULL, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_NULL, t, g_parse_context);
                 }

            YY_BREAK
          case 20: // rule sql_lexer.l:118: ASC :
            YY_USER_ACTION
#line 118 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_ASC, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_ASC, t, g_parse_context);
                 }

            YY_BREAK
          case 21: // rule sql_lexer.l:123: DESC :
            YY_USER_ACTION
#line 123 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_DESC, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_DESC, t, g_parse_context);
                 }

            YY_BREAK
          case 22: // rule sql_lexer.l:128: MIN :
            YY_USER_ACTION
#line 128 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_MIN, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_MIN, t, g_parse_context);
                 }

            YY_BREAK
          case 23: // rule sql_lexer.l:133: MAX :
            YY_USER_ACTION
#line 133 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_MAX, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_MAX, t, g_parse_context);
                 }

            YY_BREAK
          case 24: // rule sql_lexer.l:138: SUM :
            YY_USER_ACTION
#line 138 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_SUM, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_SUM, t, g_parse_context);
                 }

            YY_BREAK
          case 25: // rule sql_lexer.l:143: IN :
            YY_USER_ACTION
#line 143 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_IN, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_IN, t, g_parse_context);
                 }

            YY_BREAK
          case 26: // rule sql_lexer.l:148: PERCENTILE :
            YY_USER_ACTION
#line 148 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_PERCENTILE, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_PERCENTILE, t, g_parse_context);
                 }

            YY_BREAK
          case 27: // rule sql_lexer.l:153: COALESCE :
            YY_USER_ACTION
#line 153 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_COALESCE, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_COALESCE, t, g_parse_context);
                 }

            YY_BREAK
          case 28: // rule sql_lexer.l:158: RSUBSTR :
            YY_USER_ACTION
#line 158 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_RSUBSTR, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_RSUBSTR, t, g_parse_context);
                 }

            YY_BREAK
          case 29: // rule sql_lexer.l:163: "GROUP BY" :
            YY_USER_ACTION
#line 163 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_GROUP_BY, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_GROUP_BY, t, g_parse_context);
                 }

            YY_BREAK
          case 30: // rule sql_lexer.l:168: "ORDER BY" :
            YY_USER_ACTION
#line 168 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_ORDER_BY, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_ORDER_BY, t, g_parse_context);
                 }

            YY_BREAK
          case 31: // rule sql_lexer.l:173: "UNION ALL" :
            YY_USER_ACTION
#line 173 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_UNION_ALL, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_UNION_ALL, t, g_parse_context);
                 }

            YY_BREAK
          case 32: // rule sql_lexer.l:178: {INTEGER} :
            YY_USER_ACTION
#line 178 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_INTEGER, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_INTEGER, t, g_parse_context);
                 }

            YY_BREAK
          case 33: // rule sql_lexer.l:183: {FLOATING} :
            YY_USER_ACTION
#line 183 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_FLOATING, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_FLOATING, t, g_parse_context);
                 }

            YY_BREAK
          case 34: // rule sql_lexer.l:188: {IDENTIFIER} :
            YY_USER_ACTION
#line 188 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_IDENTIFIER, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_IDENTIFIER, t, g_parse_context);
                 }

            YY_BREAK
          case 35: // rule sql_lexer.l:193: {PATH} :
            YY_USER_ACTION
#line 193 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_PATH, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_PATH, t, g_parse_context);
                 }

            YY_BREAK
          case 36: // rule sql_lexer.l:198: {QUOTED_STRING} :
            YY_USER_ACTION
#line 198 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_STR, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_STR, t, g_parse_context);
                 }

            YY_BREAK
          case 37: // rule sql_lexer.l:203: {TIMESTAMP} :
            YY_USER_ACTION
#line 203 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_TIMESTAMP, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_TIMESTAMP, t, g_parse_context);
                 }

            YY_BREAK
          case 38: // rule sql_lexer.l:208: ";" :
            YY_USER_ACTION
#line 208 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_SEMICOLON, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_SEMICOLON, t, g_parse_context);
                 }

            YY_BREAK
          case 39: // rule sql_lexer.l:213: "," :
            YY_USER_ACTION
#line 213 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_COMMA, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_COMMA, t, g_parse_context);
                 }

            YY_BREAK
          case 40: // rule sql_lexer.l:218: "*" :
            YY_USER_ACTION
#line 218 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_STAR, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_STAR, t, g_parse_context);
                 }

            YY_BREAK
          case 41: // rule sql_lexer.l:223: "=" :
            YY_USER_ACTION
#line 223 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_EQ, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_EQ, t, g_parse_context);
                 }

            YY_BREAK
          case 42: // rule sql_lexer.l:228: "!=" :
            YY_USER_ACTION
#line 228 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_NEQ, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_NEQ, t, g_parse_context);
                 }

            YY_BREAK
          case 43: // rule sql_lexer.l:233: "(" :
            YY_USER_ACTION
#line 233 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_LPAREN, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_LPAREN, t, g_parse_context);
                 }

            YY_BREAK
          case 44: // rule sql_lexer.l:238: ")" :
            YY_USER_ACTION
#line 238 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_RPAREN, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_RPAREN, t, g_parse_context);
                 }

            YY_BREAK
          case 45: // rule sql_lexer.l:243: "!" :
            YY_USER_ACTION
#line 243 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_EXCLAMATION, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_EXCLAMATION, t, g_parse_context);
                 }

            YY_BREAK
          case 46: // rule sql_lexer.l:248: "+" :
            YY_USER_ACTION
#line 248 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_PLUS, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_PLUS, t, g_parse_context);
                 }

            YY_BREAK
          case 47: // rule sql_lexer.l:253: "/" :
            YY_USER_ACTION
#line 253 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_DIVIDE, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_DIVIDE, t, g_parse_context);
                 }

            YY_BREAK
          case 48: // rule sql_lexer.l:258: "@" :
            YY_USER_ACTION
#line 258 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_AT, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_AT, t, g_parse_context);
                 }

            YY_BREAK
          case 49: // rule sql_lexer.l:263: "$" :
            YY_USER_ACTION
#line 263 "sql_lexer.l"
{
                     lsql::sql::parse::Token t = {TOKEN_DOLLAR, strdup(yytext), (int)strlen(yytext)};
                     Parse(g_parser, TOKEN_DOLLAR, t, g_parse_context);
                 }

            YY_BREAK
          case 50: // rule sql_lexer.l:274: . :
            YY_USER_ACTION
#line 274 "sql_lexer.l"
{
                     fprintf(stderr, "lexer error: unknown character: '%s' (ASCII %d)\n", yytext, yytext[0]);
                     g_parse_context->has_error = 1;
                 }

            YY_BREAK
        }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 3: user code                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 280 "sql_lexer.l"

void set_parser_context(void* parser, lsql::sql::parse::Context* ctx) {
    g_parser = parser;
    g_parse_context = ctx;
}
