/* This file is automatically generated by Lemon from input grammar
** source file "sql_grammar.y".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifier prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 5 "sql_grammar.y"

    #include "sql/parser/token.h"
    #include "sql/parser/parser.h"

    #include "sql/ast/SelectStatement.h"
    #include "sql/ast/Expression.h"
    #include "sql/ast/BinExpression.h"
    #include "sql/ast/UnaryExpression.h"
    #include "sql/ast/UnaryAggregateExpression.h"
    #include "sql/ast/FileReference.h"
    #include "sql/ast/Program.h"

    #include <cstdio>
    #include <cstdlib>
    #include <cstring>
    #include <vector>

    namespace ast = lsql::sql::ast;
#line 49 "sql_grammar.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef TOKEN_SELECT
#define TOKEN_SELECT                    1
#define TOKEN_COUNT                     2
#define TOKEN_FROM                      3
#define TOKEN_IDENTIFIER                4
#define TOKEN_SEMICOLON                 5
#define TOKEN_EOF                       6
#define TOKEN_AS                        7
#define TOKEN_IN                        8
#define TOKEN_COALESCE                  9
#define TOKEN_COMMA                    10
#define TOKEN_STAR                     11
#define TOKEN_WHERE                    12
#define TOKEN_LIMIT                    13
#define TOKEN_INTEGER                  14
#define TOKEN_FLOATING                 15
#define TOKEN_PATH                     16
#define TOKEN_STR                      17
#define TOKEN_RSUBSTR                  18
#define TOKEN_LPAREN                   19
#define TOKEN_RPAREN                   20
#define TOKEN_AT                       21
#define TOKEN_GROUP_BY                 22
#define TOKEN_ORDER_BY                 23
#define TOKEN_TRUE                     24
#define TOKEN_FALSE                    25
#define TOKEN_DESC                     26
#define TOKEN_ASC                      27
#define TOKEN_NULL                     28
#define TOKEN_DOLLAR                   29
#define TOKEN_MIN                      30
#define TOKEN_MAX                      31
#define TOKEN_SUM                      32
#define TOKEN_PERCENTILE               33
#define TOKEN_PLUS                     34
#define TOKEN_OR                       35
#define TOKEN_AND                      36
#define TOKEN_DIVIDE                   37
#define TOKEN_EQ                       38
#define TOKEN_NEQ                      39
#define TOKEN_LIKE                     40
#define TOKEN_STRING                   41
#define TOKEN_INT                      42
#define TOKEN_FLOAT                    43
#define TOKEN_BOOL                     44
#define TOKEN_EXCLAMATION              45
#define TOKEN_TIMESTAMP                46
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYREALLOC          Name of the realloc() function to use
**    YYFREE             Name of the free() function to use
**    YYDYNSTACK         True if stack space should be extended on heap
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
**    YY_MIN_DSTRCTR     Minimum symbol value that has a destructor
**    YY_MAX_DSTRCTR     Maximum symbol value that has a destructor
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 68
#define YYACTIONTYPE unsigned char
#define ParseTOKENTYPE lsql::sql::parse::Token
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
  ast::SelectItem* yy46;
  std::vector<float>* yy49;
  int yy60;
  std::vector<std::unique_ptr<ast::Expression>>* yy64;
  std::vector<std::unique_ptr<ast::SelectItem>>* yy67;
  lsql::sql::ast::Node* yy77;
  ast::OrderBy* yy90;
  std::vector<std::unique_ptr<ast::Node>>* yy102;
  ast::Expression* yy115;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define ParseARG_SDECL lsql::sql::parse::Context *pCtx;
#define ParseARG_PDECL ,lsql::sql::parse::Context *pCtx
#define ParseARG_PARAM ,pCtx
#define ParseARG_FETCH lsql::sql::parse::Context *pCtx=yypParser->pCtx;
#define ParseARG_STORE yypParser->pCtx=pCtx;
#undef YYREALLOC
#define YYREALLOC realloc
#undef YYFREE
#define YYFREE free
#undef YYDYNSTACK
#define YYDYNSTACK 0
#undef YYSIZELIMIT
#define ParseCTX(P) 0
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#undef YYERRORSYMBOL
#undef YYERRSYMDT
#undef YYFALLBACK
#define YYNSTATE             86
#define YYNRULE              60
#define YYNRULE_WITH_ACTION  60
#define YYNTOKEN             47
#define YY_MAX_SHIFT         85
#define YY_MIN_SHIFTREDUCE   128
#define YY_MAX_SHIFTREDUCE   187
#define YY_ERROR_ACTION      188
#define YY_ACCEPT_ACTION     189
#define YY_NO_ACTION         190
#define YY_MIN_REDUCE        191
#define YY_MAX_REDUCE        250
#define YY_MIN_DSTRCTR       0
#define YY_MAX_DSTRCTR       0
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif

/* Macro to determine if stack space has the ability to grow using
** heap memory.
*/
#if YYSTACKDEPTH<=0 || YYDYNSTACK
# define YYGROWABLESTACK 1
#else
# define YYGROWABLESTACK 0
#endif

/* Guarantee a minimum number of initial stack slots.
*/
#if YYSTACKDEPTH<=0
# undef YYSTACKDEPTH
# define YYSTACKDEPTH 2  /* Need a minimum stack size */
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (282)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */    47,  196,   72,   60,   36,   11,  189,  192,  194,   68,
 /*    10 */     1,  151,    1,   84,  161,  162,   35,  160,   67,   59,
 /*    20 */   204,  215,   35,   76,  164,  165,   12,  216,  163,   37,
 /*    30 */    71,   70,   69,   64,    8,    1,   77,   63,   84,    8,
 /*    40 */    85,   81,   80,   79,   78,   19,   72,  184,   36,    9,
 /*    50 */    61,    8,   35,   68,  193,  194,    3,  220,  161,  162,
 /*    60 */    38,  160,   67,   20,   28,   26,   82,   39,  164,  165,
 /*    70 */    26,   82,  163,  186,   71,   70,   69,   64,   22,   24,
 /*    80 */    20,   28,   26,   82,   40,   81,   80,   79,   78,   19,
 /*    90 */    72,   29,  166,   57,  229,  229,   48,   68,  248,   35,
 /*   100 */    58,  198,  161,  162,  219,  160,   67,  147,  146,   62,
 /*   110 */    48,   41,  164,  165,   55,    8,  163,   30,   71,   70,
 /*   120 */    69,   64,  229,  229,  229,  229,  229,  229,    8,   81,
 /*   130 */    80,   79,   78,   19,    8,   34,   66,   42,  198,   49,
 /*   140 */   181,    8,   22,   24,   20,   28,   26,   82,   53,  195,
 /*   150 */    43,    8,  198,  180,   83,   22,   24,   20,   28,   26,
 /*   160 */    82,   22,   24,   20,   28,   26,   82,    8,   22,   24,
 /*   170 */    20,   28,   26,   82,    8,   29,   51,   44,   52,  179,
 /*   180 */     8,   28,   26,   82,   45,  182,  178,   56,    8,   46,
 /*   190 */     8,   54,  170,   50,   22,   24,   20,   28,   26,   82,
 /*   200 */   169,   22,   24,   20,   28,   26,   82,   22,   24,   20,
 /*   210 */    28,   26,   82,    8,    7,   22,   24,   20,   28,   26,
 /*   220 */    82,    8,   82,  197,    2,  168,   31,    8,    4,   32,
 /*   230 */   136,  155,   33,  167,    8,    5,  187,   13,  138,   65,
 /*   240 */    22,   24,   20,   28,   26,   82,   73,   14,   22,   24,
 /*   250 */    20,   28,   26,   82,   22,   24,   20,   28,   26,   82,
 /*   260 */    74,  183,   24,   20,   28,   26,   82,    6,   15,   16,
 /*   270 */    17,   18,  137,   21,   75,   23,   25,   27,  172,  149,
 /*   280 */    10,  191,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    47,   62,    2,   64,    4,   59,   60,   61,   62,    9,
 /*    10 */     1,   11,    1,    4,   14,   15,   47,   17,   18,   50,
 /*    20 */    67,   52,   47,   16,   24,   25,   19,   52,   28,   47,
 /*    30 */    30,   31,   32,   33,    8,    1,   29,   10,    4,    8,
 /*    40 */     6,   41,   42,   43,   44,   45,    2,   20,    4,    3,
 /*    50 */     7,    8,   47,    9,   61,   62,   10,   52,   14,   15,
 /*    60 */    47,   17,   18,   37,   38,   39,   40,   47,   24,   25,
 /*    70 */    39,   40,   28,   15,   30,   31,   32,   33,   35,   36,
 /*    80 */    37,   38,   39,   40,   47,   41,   42,   43,   44,   45,
 /*    90 */     2,   10,    4,   53,    7,    8,   47,    9,   63,   47,
 /*   100 */    51,   66,   14,   15,   52,   17,   18,   26,   27,   57,
 /*   110 */    47,   47,   24,   25,   51,    8,   28,   10,   30,   31,
 /*   120 */    32,   33,   35,   36,   37,   38,   39,   40,    8,   41,
 /*   130 */    42,   43,   44,   45,    8,   63,   10,   47,   66,   47,
 /*   140 */    20,    8,   35,   36,   37,   38,   39,   40,   47,   63,
 /*   150 */    47,    8,   66,   20,   13,   35,   36,   37,   38,   39,
 /*   160 */    40,   35,   36,   37,   38,   39,   40,    8,   35,   36,
 /*   170 */    37,   38,   39,   40,    8,   10,   47,   47,   47,   20,
 /*   180 */     8,   38,   39,   40,   47,   20,   20,   47,    8,   47,
 /*   190 */     8,   47,   20,   47,   35,   36,   37,   38,   39,   40,
 /*   200 */    20,   35,   36,   37,   38,   39,   40,   35,   36,   37,
 /*   210 */    38,   39,   40,    8,   23,   35,   36,   37,   38,   39,
 /*   220 */    40,    8,   40,   49,   22,   20,   58,    8,   12,   56,
 /*   230 */    20,    4,   65,   20,    8,   10,   15,   19,   14,   17,
 /*   240 */    35,   36,   37,   38,   39,   40,   34,   19,   35,   36,
 /*   250 */    37,   38,   39,   40,   35,   36,   37,   38,   39,   40,
 /*   260 */    46,   20,   36,   37,   38,   39,   40,   19,   19,   19,
 /*   270 */    19,   19,    4,   19,   21,   19,   19,   19,   17,   14,
 /*   280 */    38,    0,   68,   68,   68,   68,   68,   68,   68,   68,
 /*   290 */    68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
 /*   300 */    68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
 /*   310 */    68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
 /*   320 */    68,   68,   68,   68,   68,   68,   68,   68,   68,
};
#define YY_SHIFT_COUNT    (85)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (281)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */     9,    0,   44,   44,   88,   44,   88,   88,    7,    7,
 /*    10 */     7,   34,   11,   88,   88,   88,   88,   88,   88,   88,
 /*    20 */    88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
 /*    30 */    58,  141,  191,  202,  216,   43,   87,  107,  126,  120,
 /*    40 */   133,  159,  166,  172,  180,  205,  213,  219,  219,  219,
 /*    50 */   219,  226,   26,  143,   31,   81,  182,   27,  165,   46,
 /*    60 */   210,  227,  225,  221,  218,  241,  222,  228,  248,  249,
 /*    70 */   250,  251,  252,  224,  212,  214,  253,  268,  254,  256,
 /*    80 */   257,  258,  261,  265,  242,  281,
};
#define YY_REDUCE_COUNT (34)
#define YY_REDUCE_MIN   (-61)
#define YY_REDUCE_MAX   (174)
static const short yy_reduce_ofst[] = {
 /*     0 */   -54,  -31,   52,  -25,  -47,    5,   49,   63,   35,   72,
 /*    10 */    86,   -7,  -61,  -18,   13,   20,   37,   64,   90,   92,
 /*    20 */   101,  103,  129,  130,  131,  137,  140,  142,  144,  146,
 /*    30 */    40,  174,  168,  173,  167,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
 /*    10 */   188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
 /*    20 */   188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
 /*    30 */   188,  213,  207,  205,  203,  188,  217,  188,  188,  188,
 /*    40 */   188,  188,  188,  188,  188,  188,  188,  211,  221,  234,
 /*    50 */   222,  239,  238,  240,  236,  208,  237,  188,  188,  188,
 /*    60 */   188,  188,  206,  188,  188,  188,  188,  188,  188,  188,
 /*    70 */   188,  188,  188,  188,  188,  188,  202,  188,  188,  188,
 /*    80 */   188,  188,  188,  188,  188,  188,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
  yyStackEntry *yystackEnd;           /* Last entry in the stack */
  yyStackEntry *yystack;              /* The parser stack */
  yyStackEntry yystk0[YYSTACKDEPTH];  /* Initial stack space */
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "TOKEN_SELECT",
  /*    2 */ "TOKEN_COUNT",
  /*    3 */ "TOKEN_FROM",
  /*    4 */ "TOKEN_IDENTIFIER",
  /*    5 */ "TOKEN_SEMICOLON",
  /*    6 */ "TOKEN_EOF",
  /*    7 */ "TOKEN_AS",
  /*    8 */ "TOKEN_IN",
  /*    9 */ "TOKEN_COALESCE",
  /*   10 */ "TOKEN_COMMA",
  /*   11 */ "TOKEN_STAR",
  /*   12 */ "TOKEN_WHERE",
  /*   13 */ "TOKEN_LIMIT",
  /*   14 */ "TOKEN_INTEGER",
  /*   15 */ "TOKEN_FLOATING",
  /*   16 */ "TOKEN_PATH",
  /*   17 */ "TOKEN_STR",
  /*   18 */ "TOKEN_RSUBSTR",
  /*   19 */ "TOKEN_LPAREN",
  /*   20 */ "TOKEN_RPAREN",
  /*   21 */ "TOKEN_AT",
  /*   22 */ "TOKEN_GROUP_BY",
  /*   23 */ "TOKEN_ORDER_BY",
  /*   24 */ "TOKEN_TRUE",
  /*   25 */ "TOKEN_FALSE",
  /*   26 */ "TOKEN_DESC",
  /*   27 */ "TOKEN_ASC",
  /*   28 */ "TOKEN_NULL",
  /*   29 */ "TOKEN_DOLLAR",
  /*   30 */ "TOKEN_MIN",
  /*   31 */ "TOKEN_MAX",
  /*   32 */ "TOKEN_SUM",
  /*   33 */ "TOKEN_PERCENTILE",
  /*   34 */ "TOKEN_PLUS",
  /*   35 */ "TOKEN_OR",
  /*   36 */ "TOKEN_AND",
  /*   37 */ "TOKEN_DIVIDE",
  /*   38 */ "TOKEN_EQ",
  /*   39 */ "TOKEN_NEQ",
  /*   40 */ "TOKEN_LIKE",
  /*   41 */ "TOKEN_STRING",
  /*   42 */ "TOKEN_INT",
  /*   43 */ "TOKEN_FLOAT",
  /*   44 */ "TOKEN_BOOL",
  /*   45 */ "TOKEN_EXCLAMATION",
  /*   46 */ "TOKEN_TIMESTAMP",
  /*   47 */ "expression",
  /*   48 */ "group_expression",
  /*   49 */ "limit_opt",
  /*   50 */ "select_list",
  /*   51 */ "expression_list",
  /*   52 */ "select_item",
  /*   53 */ "floating_list",
  /*   54 */ "group_select_list",
  /*   55 */ "group_select_item",
  /*   56 */ "group_by_opt",
  /*   57 */ "group_by_list",
  /*   58 */ "order_by_opt",
  /*   59 */ "statement_list",
  /*   60 */ "input",
  /*   61 */ "statement",
  /*   62 */ "select_statement",
  /*   63 */ "select_source",
  /*   64 */ "relation",
  /*   65 */ "where_opt",
  /*   66 */ "file_source",
  /*   67 */ "condition",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "input ::= statement_list TOKEN_EOF",
 /*   1 */ "statement_list ::= statement",
 /*   2 */ "statement_list ::= statement_list statement",
 /*   3 */ "statement ::= select_statement",
 /*   4 */ "statement ::= TOKEN_IDENTIFIER TOKEN_EQ select_source",
 /*   5 */ "relation ::= select_statement",
 /*   6 */ "select_statement ::= TOKEN_SELECT select_list TOKEN_FROM select_source where_opt group_by_opt order_by_opt limit_opt",
 /*   7 */ "select_source ::= file_source",
 /*   8 */ "select_source ::= TOKEN_LPAREN relation TOKEN_RPAREN",
 /*   9 */ "select_source ::= TOKEN_DOLLAR TOKEN_IDENTIFIER",
 /*  10 */ "file_source ::= TOKEN_PATH TOKEN_AT TOKEN_TIMESTAMP TOKEN_PLUS TOKEN_INTEGER",
 /*  11 */ "file_source ::= TOKEN_PATH",
 /*  12 */ "where_opt ::=",
 /*  13 */ "where_opt ::= TOKEN_WHERE condition",
 /*  14 */ "group_by_opt ::=",
 /*  15 */ "group_by_opt ::= TOKEN_GROUP_BY group_by_list",
 /*  16 */ "order_by_opt ::=",
 /*  17 */ "order_by_opt ::= TOKEN_ORDER_BY expression_list",
 /*  18 */ "order_by_opt ::= TOKEN_ORDER_BY expression_list TOKEN_ASC",
 /*  19 */ "order_by_opt ::= TOKEN_ORDER_BY expression_list TOKEN_DESC",
 /*  20 */ "condition ::= expression",
 /*  21 */ "limit_opt ::= TOKEN_LIMIT TOKEN_INTEGER",
 /*  22 */ "limit_opt ::=",
 /*  23 */ "select_list ::= TOKEN_STAR",
 /*  24 */ "select_list ::= select_item",
 /*  25 */ "select_list ::= select_list TOKEN_COMMA select_item",
 /*  26 */ "select_item ::= TOKEN_IDENTIFIER",
 /*  27 */ "select_item ::= expression TOKEN_AS TOKEN_IDENTIFIER",
 /*  28 */ "group_by_list ::= select_item",
 /*  29 */ "group_by_list ::= group_by_list TOKEN_COMMA select_item",
 /*  30 */ "expression_list ::= expression",
 /*  31 */ "expression_list ::= expression_list TOKEN_COMMA expression",
 /*  32 */ "expression ::= TOKEN_STR",
 /*  33 */ "expression ::= TOKEN_INTEGER",
 /*  34 */ "expression ::= TOKEN_FLOATING",
 /*  35 */ "expression ::= TOKEN_NULL",
 /*  36 */ "expression ::= TOKEN_TRUE",
 /*  37 */ "expression ::= TOKEN_FALSE",
 /*  38 */ "expression ::= TOKEN_IDENTIFIER",
 /*  39 */ "expression ::= TOKEN_STRING TOKEN_LPAREN expression TOKEN_RPAREN",
 /*  40 */ "expression ::= TOKEN_INT TOKEN_LPAREN expression TOKEN_RPAREN",
 /*  41 */ "expression ::= TOKEN_FLOAT TOKEN_LPAREN expression TOKEN_RPAREN",
 /*  42 */ "expression ::= TOKEN_BOOL TOKEN_LPAREN expression TOKEN_RPAREN",
 /*  43 */ "expression ::= TOKEN_EXCLAMATION expression",
 /*  44 */ "expression ::= expression TOKEN_LIKE TOKEN_STR",
 /*  45 */ "expression ::= expression TOKEN_EQ expression",
 /*  46 */ "expression ::= expression TOKEN_NEQ expression",
 /*  47 */ "expression ::= expression TOKEN_AND expression",
 /*  48 */ "expression ::= expression TOKEN_OR expression",
 /*  49 */ "expression ::= expression TOKEN_DIVIDE expression",
 /*  50 */ "expression ::= TOKEN_COUNT TOKEN_LPAREN expression TOKEN_RPAREN",
 /*  51 */ "expression ::= TOKEN_MIN TOKEN_LPAREN expression TOKEN_RPAREN",
 /*  52 */ "expression ::= TOKEN_MAX TOKEN_LPAREN expression TOKEN_RPAREN",
 /*  53 */ "expression ::= TOKEN_SUM TOKEN_LPAREN expression TOKEN_RPAREN",
 /*  54 */ "expression ::= TOKEN_COALESCE TOKEN_LPAREN expression_list TOKEN_RPAREN",
 /*  55 */ "expression ::= TOKEN_RSUBSTR TOKEN_LPAREN expression TOKEN_COMMA TOKEN_STR TOKEN_RPAREN",
 /*  56 */ "expression ::= TOKEN_PERCENTILE TOKEN_LPAREN expression TOKEN_COMMA floating_list TOKEN_RPAREN",
 /*  57 */ "expression ::= expression TOKEN_IN select_source",
 /*  58 */ "floating_list ::= TOKEN_FLOATING",
 /*  59 */ "floating_list ::= floating_list TOKEN_COMMA TOKEN_FLOATING",
};
#endif /* NDEBUG */


#if YYGROWABLESTACK
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int oldSize = 1 + (int)(p->yystackEnd - p->yystack);
  int newSize;
  int idx;
  yyStackEntry *pNew;
#ifdef YYSIZELIMIT
  int nLimit = YYSIZELIMIT(ParseCTX(p));
#endif

  newSize = oldSize*2 + 100;
#ifdef YYSIZELIMIT
  if( newSize>nLimit ){
    newSize = nLimit;
    if( newSize<=oldSize ) return 1;
  }
#endif
  idx = (int)(p->yytos - p->yystack);
  if( p->yystack==p->yystk0 ){
    pNew = YYREALLOC(0, newSize*sizeof(pNew[0]), ParseCTX(p));
    if( pNew==0 ) return 1;
    memcpy(pNew, p->yystack, oldSize*sizeof(pNew[0]));
  }else{
    pNew = YYREALLOC(p->yystack, newSize*sizeof(pNew[0]), ParseCTX(p));
    if( pNew==0 ) return 1;
  }
  p->yystack = pNew;
  p->yytos = &p->yystack[idx];
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
            yyTracePrompt, oldSize, newSize);
  }
#endif
  p->yystackEnd = &p->yystack[newSize-1];
  return 0;
}
#endif /* YYGROWABLESTACK */

#if !YYGROWABLESTACK
/* For builds that do no have a growable stack, yyGrowStack always
** returns an error.
*/
# define yyGrowStack(X) 1
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
  yypParser->yystack = yypParser->yystk0;
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;

  /* In-lined version of calling yy_pop_parser_stack() for each
  ** element left in the stack */
  yyStackEntry *yytos = pParser->yytos;
  while( yytos>pParser->yystack ){
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sPopping %s\n",
        yyTracePrompt,
        yyTokenName[yytos->major]);
    }
#endif
    if( yytos->major>=YY_MIN_DSTRCTR ){
      yy_destructor(pParser, yytos->major, &yytos->minor);
    }
    yytos--;
  }

#if YYGROWABLESTACK
  if( pParser->yystack!=pParser->yystk0 ){
    YYFREE(pParser->yystack, ParseCTX(pParser));
  }
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
  yytos = yypParser->yytos;
  if( yytos>yypParser->yystackEnd ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
    yytos = yypParser->yytos;
    assert( yytos <= yypParser->yystackEnd );
  }
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    60,  /* (0) input ::= statement_list TOKEN_EOF */
    59,  /* (1) statement_list ::= statement */
    59,  /* (2) statement_list ::= statement_list statement */
    61,  /* (3) statement ::= select_statement */
    61,  /* (4) statement ::= TOKEN_IDENTIFIER TOKEN_EQ select_source */
    64,  /* (5) relation ::= select_statement */
    62,  /* (6) select_statement ::= TOKEN_SELECT select_list TOKEN_FROM select_source where_opt group_by_opt order_by_opt limit_opt */
    63,  /* (7) select_source ::= file_source */
    63,  /* (8) select_source ::= TOKEN_LPAREN relation TOKEN_RPAREN */
    63,  /* (9) select_source ::= TOKEN_DOLLAR TOKEN_IDENTIFIER */
    66,  /* (10) file_source ::= TOKEN_PATH TOKEN_AT TOKEN_TIMESTAMP TOKEN_PLUS TOKEN_INTEGER */
    66,  /* (11) file_source ::= TOKEN_PATH */
    65,  /* (12) where_opt ::= */
    65,  /* (13) where_opt ::= TOKEN_WHERE condition */
    56,  /* (14) group_by_opt ::= */
    56,  /* (15) group_by_opt ::= TOKEN_GROUP_BY group_by_list */
    58,  /* (16) order_by_opt ::= */
    58,  /* (17) order_by_opt ::= TOKEN_ORDER_BY expression_list */
    58,  /* (18) order_by_opt ::= TOKEN_ORDER_BY expression_list TOKEN_ASC */
    58,  /* (19) order_by_opt ::= TOKEN_ORDER_BY expression_list TOKEN_DESC */
    67,  /* (20) condition ::= expression */
    49,  /* (21) limit_opt ::= TOKEN_LIMIT TOKEN_INTEGER */
    49,  /* (22) limit_opt ::= */
    50,  /* (23) select_list ::= TOKEN_STAR */
    50,  /* (24) select_list ::= select_item */
    50,  /* (25) select_list ::= select_list TOKEN_COMMA select_item */
    52,  /* (26) select_item ::= TOKEN_IDENTIFIER */
    52,  /* (27) select_item ::= expression TOKEN_AS TOKEN_IDENTIFIER */
    57,  /* (28) group_by_list ::= select_item */
    57,  /* (29) group_by_list ::= group_by_list TOKEN_COMMA select_item */
    51,  /* (30) expression_list ::= expression */
    51,  /* (31) expression_list ::= expression_list TOKEN_COMMA expression */
    47,  /* (32) expression ::= TOKEN_STR */
    47,  /* (33) expression ::= TOKEN_INTEGER */
    47,  /* (34) expression ::= TOKEN_FLOATING */
    47,  /* (35) expression ::= TOKEN_NULL */
    47,  /* (36) expression ::= TOKEN_TRUE */
    47,  /* (37) expression ::= TOKEN_FALSE */
    47,  /* (38) expression ::= TOKEN_IDENTIFIER */
    47,  /* (39) expression ::= TOKEN_STRING TOKEN_LPAREN expression TOKEN_RPAREN */
    47,  /* (40) expression ::= TOKEN_INT TOKEN_LPAREN expression TOKEN_RPAREN */
    47,  /* (41) expression ::= TOKEN_FLOAT TOKEN_LPAREN expression TOKEN_RPAREN */
    47,  /* (42) expression ::= TOKEN_BOOL TOKEN_LPAREN expression TOKEN_RPAREN */
    47,  /* (43) expression ::= TOKEN_EXCLAMATION expression */
    47,  /* (44) expression ::= expression TOKEN_LIKE TOKEN_STR */
    47,  /* (45) expression ::= expression TOKEN_EQ expression */
    47,  /* (46) expression ::= expression TOKEN_NEQ expression */
    47,  /* (47) expression ::= expression TOKEN_AND expression */
    47,  /* (48) expression ::= expression TOKEN_OR expression */
    47,  /* (49) expression ::= expression TOKEN_DIVIDE expression */
    47,  /* (50) expression ::= TOKEN_COUNT TOKEN_LPAREN expression TOKEN_RPAREN */
    47,  /* (51) expression ::= TOKEN_MIN TOKEN_LPAREN expression TOKEN_RPAREN */
    47,  /* (52) expression ::= TOKEN_MAX TOKEN_LPAREN expression TOKEN_RPAREN */
    47,  /* (53) expression ::= TOKEN_SUM TOKEN_LPAREN expression TOKEN_RPAREN */
    47,  /* (54) expression ::= TOKEN_COALESCE TOKEN_LPAREN expression_list TOKEN_RPAREN */
    47,  /* (55) expression ::= TOKEN_RSUBSTR TOKEN_LPAREN expression TOKEN_COMMA TOKEN_STR TOKEN_RPAREN */
    47,  /* (56) expression ::= TOKEN_PERCENTILE TOKEN_LPAREN expression TOKEN_COMMA floating_list TOKEN_RPAREN */
    47,  /* (57) expression ::= expression TOKEN_IN select_source */
    53,  /* (58) floating_list ::= TOKEN_FLOATING */
    53,  /* (59) floating_list ::= floating_list TOKEN_COMMA TOKEN_FLOATING */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -2,  /* (0) input ::= statement_list TOKEN_EOF */
   -1,  /* (1) statement_list ::= statement */
   -2,  /* (2) statement_list ::= statement_list statement */
   -1,  /* (3) statement ::= select_statement */
   -3,  /* (4) statement ::= TOKEN_IDENTIFIER TOKEN_EQ select_source */
   -1,  /* (5) relation ::= select_statement */
   -8,  /* (6) select_statement ::= TOKEN_SELECT select_list TOKEN_FROM select_source where_opt group_by_opt order_by_opt limit_opt */
   -1,  /* (7) select_source ::= file_source */
   -3,  /* (8) select_source ::= TOKEN_LPAREN relation TOKEN_RPAREN */
   -2,  /* (9) select_source ::= TOKEN_DOLLAR TOKEN_IDENTIFIER */
   -5,  /* (10) file_source ::= TOKEN_PATH TOKEN_AT TOKEN_TIMESTAMP TOKEN_PLUS TOKEN_INTEGER */
   -1,  /* (11) file_source ::= TOKEN_PATH */
    0,  /* (12) where_opt ::= */
   -2,  /* (13) where_opt ::= TOKEN_WHERE condition */
    0,  /* (14) group_by_opt ::= */
   -2,  /* (15) group_by_opt ::= TOKEN_GROUP_BY group_by_list */
    0,  /* (16) order_by_opt ::= */
   -2,  /* (17) order_by_opt ::= TOKEN_ORDER_BY expression_list */
   -3,  /* (18) order_by_opt ::= TOKEN_ORDER_BY expression_list TOKEN_ASC */
   -3,  /* (19) order_by_opt ::= TOKEN_ORDER_BY expression_list TOKEN_DESC */
   -1,  /* (20) condition ::= expression */
   -2,  /* (21) limit_opt ::= TOKEN_LIMIT TOKEN_INTEGER */
    0,  /* (22) limit_opt ::= */
   -1,  /* (23) select_list ::= TOKEN_STAR */
   -1,  /* (24) select_list ::= select_item */
   -3,  /* (25) select_list ::= select_list TOKEN_COMMA select_item */
   -1,  /* (26) select_item ::= TOKEN_IDENTIFIER */
   -3,  /* (27) select_item ::= expression TOKEN_AS TOKEN_IDENTIFIER */
   -1,  /* (28) group_by_list ::= select_item */
   -3,  /* (29) group_by_list ::= group_by_list TOKEN_COMMA select_item */
   -1,  /* (30) expression_list ::= expression */
   -3,  /* (31) expression_list ::= expression_list TOKEN_COMMA expression */
   -1,  /* (32) expression ::= TOKEN_STR */
   -1,  /* (33) expression ::= TOKEN_INTEGER */
   -1,  /* (34) expression ::= TOKEN_FLOATING */
   -1,  /* (35) expression ::= TOKEN_NULL */
   -1,  /* (36) expression ::= TOKEN_TRUE */
   -1,  /* (37) expression ::= TOKEN_FALSE */
   -1,  /* (38) expression ::= TOKEN_IDENTIFIER */
   -4,  /* (39) expression ::= TOKEN_STRING TOKEN_LPAREN expression TOKEN_RPAREN */
   -4,  /* (40) expression ::= TOKEN_INT TOKEN_LPAREN expression TOKEN_RPAREN */
   -4,  /* (41) expression ::= TOKEN_FLOAT TOKEN_LPAREN expression TOKEN_RPAREN */
   -4,  /* (42) expression ::= TOKEN_BOOL TOKEN_LPAREN expression TOKEN_RPAREN */
   -2,  /* (43) expression ::= TOKEN_EXCLAMATION expression */
   -3,  /* (44) expression ::= expression TOKEN_LIKE TOKEN_STR */
   -3,  /* (45) expression ::= expression TOKEN_EQ expression */
   -3,  /* (46) expression ::= expression TOKEN_NEQ expression */
   -3,  /* (47) expression ::= expression TOKEN_AND expression */
   -3,  /* (48) expression ::= expression TOKEN_OR expression */
   -3,  /* (49) expression ::= expression TOKEN_DIVIDE expression */
   -4,  /* (50) expression ::= TOKEN_COUNT TOKEN_LPAREN expression TOKEN_RPAREN */
   -4,  /* (51) expression ::= TOKEN_MIN TOKEN_LPAREN expression TOKEN_RPAREN */
   -4,  /* (52) expression ::= TOKEN_MAX TOKEN_LPAREN expression TOKEN_RPAREN */
   -4,  /* (53) expression ::= TOKEN_SUM TOKEN_LPAREN expression TOKEN_RPAREN */
   -4,  /* (54) expression ::= TOKEN_COALESCE TOKEN_LPAREN expression_list TOKEN_RPAREN */
   -6,  /* (55) expression ::= TOKEN_RSUBSTR TOKEN_LPAREN expression TOKEN_COMMA TOKEN_STR TOKEN_RPAREN */
   -6,  /* (56) expression ::= TOKEN_PERCENTILE TOKEN_LPAREN expression TOKEN_COMMA floating_list TOKEN_RPAREN */
   -3,  /* (57) expression ::= expression TOKEN_IN select_source */
   -1,  /* (58) floating_list ::= TOKEN_FLOATING */
   -3,  /* (59) floating_list ::= floating_list TOKEN_COMMA TOKEN_FLOATING */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* input ::= statement_list TOKEN_EOF */
#line 89 "sql_grammar.y"
{
    pCtx->root = std::make_unique<ast::Program>(yymsp[-1].minor.yy102);
}
#line 1239 "sql_grammar.c"
        break;
      case 1: /* statement_list ::= statement */
#line 93 "sql_grammar.y"
{
    yylhsminor.yy102 = new std::vector<std::unique_ptr<ast::Node>>();
    yylhsminor.yy102->emplace_back(yymsp[0].minor.yy77);
}
#line 1247 "sql_grammar.c"
  yymsp[0].minor.yy102 = yylhsminor.yy102;
        break;
      case 2: /* statement_list ::= statement_list statement */
#line 98 "sql_grammar.y"
{
    yylhsminor.yy102 = yymsp[-1].minor.yy102;
    yylhsminor.yy102->emplace_back(yymsp[0].minor.yy77);
}
#line 1256 "sql_grammar.c"
  yymsp[-1].minor.yy102 = yylhsminor.yy102;
        break;
      case 3: /* statement ::= select_statement */
      case 5: /* relation ::= select_statement */ yytestcase(yyruleno==5);
      case 7: /* select_source ::= file_source */ yytestcase(yyruleno==7);
#line 103 "sql_grammar.y"
{ yylhsminor.yy77 = yymsp[0].minor.yy77; }
#line 1264 "sql_grammar.c"
  yymsp[0].minor.yy77 = yylhsminor.yy77;
        break;
      case 4: /* statement ::= TOKEN_IDENTIFIER TOKEN_EQ select_source */
#line 104 "sql_grammar.y"
{
    yylhsminor.yy77 = new ast::NamedRelation(yymsp[-2].minor.yy0.text, std::unique_ptr<ast::Node>(yymsp[0].minor.yy77));
}
#line 1272 "sql_grammar.c"
  yymsp[-2].minor.yy77 = yylhsminor.yy77;
        break;
      case 6: /* select_statement ::= TOKEN_SELECT select_list TOKEN_FROM select_source where_opt group_by_opt order_by_opt limit_opt */
#line 117 "sql_grammar.y"
{
    yymsp[-7].minor.yy77 = yymsp[-4].minor.yy77;

    if (yymsp[-3].minor.yy77 != nullptr) {
        yymsp[-7].minor.yy77 = new ast::Where(std::unique_ptr<ast::Node>(yymsp[-3].minor.yy77), std::unique_ptr<ast::Node>(yymsp[-7].minor.yy77));
    }

    if (yymsp[-2].minor.yy67 != nullptr) {
        yymsp[-7].minor.yy77 = new ast::GroupBySelect(
            yymsp[-2].minor.yy67,
            yymsp[-6].minor.yy67,
            std::unique_ptr<ast::Node>(yymsp[-7].minor.yy77)
        );
    } else {
        yymsp[-7].minor.yy77 = new ast::SelectStatement(yymsp[-6].minor.yy67, std::unique_ptr<ast::Node>(yymsp[-7].minor.yy77));
    }

    if (yymsp[-1].minor.yy90 != nullptr) {
        yymsp[-7].minor.yy77 = new ast::OrderBySelect(std::unique_ptr<ast::Node>(yymsp[-7].minor.yy77), std::unique_ptr<ast::OrderBy>(yymsp[-1].minor.yy90));
    }

    if (yymsp[0].minor.yy60 != -1) {
        yymsp[-7].minor.yy77 = new ast::Limit(yymsp[0].minor.yy60, std::unique_ptr<ast::Node>(yymsp[-7].minor.yy77));
    }
}
#line 1302 "sql_grammar.c"
        break;
      case 8: /* select_source ::= TOKEN_LPAREN relation TOKEN_RPAREN */
#line 144 "sql_grammar.y"
{ yymsp[-2].minor.yy77 = yymsp[-1].minor.yy77; }
#line 1307 "sql_grammar.c"
        break;
      case 9: /* select_source ::= TOKEN_DOLLAR TOKEN_IDENTIFIER */
#line 145 "sql_grammar.y"
{
    yymsp[-1].minor.yy77 = new ast::NamedRelationReference(yymsp[0].minor.yy0.text);
}
#line 1314 "sql_grammar.c"
        break;
      case 10: /* file_source ::= TOKEN_PATH TOKEN_AT TOKEN_TIMESTAMP TOKEN_PLUS TOKEN_INTEGER */
#line 149 "sql_grammar.y"
{
    yylhsminor.yy77 = new ast::FileIntervalReference(
        std::string(yymsp[-4].minor.yy0.text),
        std::string(yymsp[-2].minor.yy0.text),
        std::stoi(yymsp[0].minor.yy0.text)
    );
}
#line 1325 "sql_grammar.c"
  yymsp[-4].minor.yy77 = yylhsminor.yy77;
        break;
      case 11: /* file_source ::= TOKEN_PATH */
#line 157 "sql_grammar.y"
{
    yylhsminor.yy77 = new ast::FileReference(std::string(yymsp[0].minor.yy0.text));
}
#line 1333 "sql_grammar.c"
  yymsp[0].minor.yy77 = yylhsminor.yy77;
        break;
      case 12: /* where_opt ::= */
#line 161 "sql_grammar.y"
{ yymsp[1].minor.yy77 = nullptr; }
#line 1339 "sql_grammar.c"
        break;
      case 13: /* where_opt ::= TOKEN_WHERE condition */
#line 162 "sql_grammar.y"
{ yymsp[-1].minor.yy77 = yymsp[0].minor.yy77; }
#line 1344 "sql_grammar.c"
        break;
      case 14: /* group_by_opt ::= */
#line 164 "sql_grammar.y"
{ yymsp[1].minor.yy67 = nullptr; }
#line 1349 "sql_grammar.c"
        break;
      case 15: /* group_by_opt ::= TOKEN_GROUP_BY group_by_list */
#line 165 "sql_grammar.y"
{ yymsp[-1].minor.yy67 = yymsp[0].minor.yy67; }
#line 1354 "sql_grammar.c"
        break;
      case 16: /* order_by_opt ::= */
#line 167 "sql_grammar.y"
{ yymsp[1].minor.yy90 = nullptr; }
#line 1359 "sql_grammar.c"
        break;
      case 17: /* order_by_opt ::= TOKEN_ORDER_BY expression_list */
#line 168 "sql_grammar.y"
{ yymsp[-1].minor.yy90 = new ast::OrderBy(yymsp[0].minor.yy64, false); }
#line 1364 "sql_grammar.c"
        break;
      case 18: /* order_by_opt ::= TOKEN_ORDER_BY expression_list TOKEN_ASC */
#line 169 "sql_grammar.y"
{ yymsp[-2].minor.yy90 = new ast::OrderBy(yymsp[-1].minor.yy64, false); }
#line 1369 "sql_grammar.c"
        break;
      case 19: /* order_by_opt ::= TOKEN_ORDER_BY expression_list TOKEN_DESC */
#line 170 "sql_grammar.y"
{ yymsp[-2].minor.yy90 = new ast::OrderBy(yymsp[-1].minor.yy64, true); }
#line 1374 "sql_grammar.c"
        break;
      case 20: /* condition ::= expression */
#line 172 "sql_grammar.y"
{ yylhsminor.yy77 = yymsp[0].minor.yy115; }
#line 1379 "sql_grammar.c"
  yymsp[0].minor.yy77 = yylhsminor.yy77;
        break;
      case 21: /* limit_opt ::= TOKEN_LIMIT TOKEN_INTEGER */
#line 174 "sql_grammar.y"
{ yymsp[-1].minor.yy60 = std::atoi(yymsp[0].minor.yy0.text); }
#line 1385 "sql_grammar.c"
        break;
      case 22: /* limit_opt ::= */
#line 175 "sql_grammar.y"
{ yymsp[1].minor.yy60 = -1; }
#line 1390 "sql_grammar.c"
        break;
      case 23: /* select_list ::= TOKEN_STAR */
#line 177 "sql_grammar.y"
{
    yymsp[0].minor.yy67 = new ast::SelectList();
}
#line 1397 "sql_grammar.c"
        break;
      case 24: /* select_list ::= select_item */
      case 28: /* group_by_list ::= select_item */ yytestcase(yyruleno==28);
#line 181 "sql_grammar.y"
{
    yylhsminor.yy67 = new ast::SelectList();
    yylhsminor.yy67->push_back(std::unique_ptr<ast::SelectItem>(yymsp[0].minor.yy46));
}
#line 1406 "sql_grammar.c"
  yymsp[0].minor.yy67 = yylhsminor.yy67;
        break;
      case 25: /* select_list ::= select_list TOKEN_COMMA select_item */
      case 29: /* group_by_list ::= group_by_list TOKEN_COMMA select_item */ yytestcase(yyruleno==29);
#line 186 "sql_grammar.y"
{
    yylhsminor.yy67 = yymsp[-2].minor.yy67;
    yylhsminor.yy67->push_back(std::unique_ptr<ast::SelectItem>(yymsp[0].minor.yy46));
}
#line 1416 "sql_grammar.c"
  yymsp[-2].minor.yy67 = yylhsminor.yy67;
        break;
      case 26: /* select_item ::= TOKEN_IDENTIFIER */
#line 191 "sql_grammar.y"
{
    yylhsminor.yy46 = new ast::SelectItem(
        std::make_unique<ast::IdentifierExpression>(yymsp[0].minor.yy0.text, lsql::ValueType::String),
        std::string(yymsp[0].minor.yy0.text)
    );
}
#line 1427 "sql_grammar.c"
  yymsp[0].minor.yy46 = yylhsminor.yy46;
        break;
      case 27: /* select_item ::= expression TOKEN_AS TOKEN_IDENTIFIER */
#line 198 "sql_grammar.y"
{
    yylhsminor.yy46 = new ast::SelectItem(std::unique_ptr<ast::Expression>(yymsp[-2].minor.yy115), std::string(yymsp[0].minor.yy0.text));
}
#line 1435 "sql_grammar.c"
  yymsp[-2].minor.yy46 = yylhsminor.yy46;
        break;
      case 30: /* expression_list ::= expression */
#line 212 "sql_grammar.y"
{
    yylhsminor.yy64 = new ast::ExpressionList();
    yylhsminor.yy64->push_back(std::unique_ptr<ast::Expression>(yymsp[0].minor.yy115));
}
#line 1444 "sql_grammar.c"
  yymsp[0].minor.yy64 = yylhsminor.yy64;
        break;
      case 31: /* expression_list ::= expression_list TOKEN_COMMA expression */
#line 217 "sql_grammar.y"
{
    yylhsminor.yy64 = yymsp[-2].minor.yy64;
    yylhsminor.yy64->push_back(std::unique_ptr<ast::Expression>(yymsp[0].minor.yy115));
}
#line 1453 "sql_grammar.c"
  yymsp[-2].minor.yy64 = yylhsminor.yy64;
        break;
      case 32: /* expression ::= TOKEN_STR */
#line 223 "sql_grammar.y"
{
    yylhsminor.yy115 = new ast::ValueExpression(yymsp[0].minor.yy0.text, lsql::ValueType::String);
}
#line 1461 "sql_grammar.c"
  yymsp[0].minor.yy115 = yylhsminor.yy115;
        break;
      case 33: /* expression ::= TOKEN_INTEGER */
#line 227 "sql_grammar.y"
{
    yylhsminor.yy115 = new ast::ValueExpression(yymsp[0].minor.yy0.text, lsql::ValueType::Integer);
}
#line 1469 "sql_grammar.c"
  yymsp[0].minor.yy115 = yylhsminor.yy115;
        break;
      case 34: /* expression ::= TOKEN_FLOATING */
#line 231 "sql_grammar.y"
{
    yylhsminor.yy115 = new ast::ValueExpression(yymsp[0].minor.yy0.text, lsql::ValueType::Floating);
}
#line 1477 "sql_grammar.c"
  yymsp[0].minor.yy115 = yylhsminor.yy115;
        break;
      case 35: /* expression ::= TOKEN_NULL */
#line 235 "sql_grammar.y"
{
    yymsp[0].minor.yy115 = new ast::ValueExpression("", lsql::ValueType::Null);
}
#line 1485 "sql_grammar.c"
        break;
      case 36: /* expression ::= TOKEN_TRUE */
      case 37: /* expression ::= TOKEN_FALSE */ yytestcase(yyruleno==37);
#line 239 "sql_grammar.y"
{
    yylhsminor.yy115 = new ast::ValueExpression(yymsp[0].minor.yy0.text, lsql::ValueType::Boolean);
}
#line 1493 "sql_grammar.c"
  yymsp[0].minor.yy115 = yylhsminor.yy115;
        break;
      case 38: /* expression ::= TOKEN_IDENTIFIER */
#line 247 "sql_grammar.y"
{
    yylhsminor.yy115 = new ast::IdentifierExpression(yymsp[0].minor.yy0.text, lsql::ValueType::String);
}
#line 1501 "sql_grammar.c"
  yymsp[0].minor.yy115 = yylhsminor.yy115;
        break;
      case 39: /* expression ::= TOKEN_STRING TOKEN_LPAREN expression TOKEN_RPAREN */
#line 251 "sql_grammar.y"
{
    yymsp[-3].minor.yy115 = new ast::CastExpression(std::unique_ptr<ast::Expression>(yymsp[-1].minor.yy115), lsql::ValueType::String);
}
#line 1509 "sql_grammar.c"
        break;
      case 40: /* expression ::= TOKEN_INT TOKEN_LPAREN expression TOKEN_RPAREN */
#line 255 "sql_grammar.y"
{
    yymsp[-3].minor.yy115 = new ast::CastExpression(std::unique_ptr<ast::Expression>(yymsp[-1].minor.yy115), lsql::ValueType::Integer);
}
#line 1516 "sql_grammar.c"
        break;
      case 41: /* expression ::= TOKEN_FLOAT TOKEN_LPAREN expression TOKEN_RPAREN */
#line 259 "sql_grammar.y"
{
    yymsp[-3].minor.yy115 = new ast::CastExpression(std::unique_ptr<ast::Expression>(yymsp[-1].minor.yy115), lsql::ValueType::Floating);
}
#line 1523 "sql_grammar.c"
        break;
      case 42: /* expression ::= TOKEN_BOOL TOKEN_LPAREN expression TOKEN_RPAREN */
#line 263 "sql_grammar.y"
{
    yymsp[-3].minor.yy115 = new ast::CastExpression(std::unique_ptr<ast::Expression>(yymsp[-1].minor.yy115), lsql::ValueType::Boolean);
}
#line 1530 "sql_grammar.c"
        break;
      case 43: /* expression ::= TOKEN_EXCLAMATION expression */
#line 267 "sql_grammar.y"
{
    yymsp[-1].minor.yy115 = new ast::UnaryExpression(
        std::unique_ptr<ast::Expression>(yymsp[0].minor.yy115),
        ast::UnaryExpressionType::BooleanNegate
    );
}
#line 1540 "sql_grammar.c"
        break;
      case 44: /* expression ::= expression TOKEN_LIKE TOKEN_STR */
#line 274 "sql_grammar.y"
{
    auto str = std::string(yymsp[0].minor.yy0.text);

    yylhsminor.yy115 = new ast::LikeExpression(
        std::unique_ptr<ast::Expression>(yymsp[-2].minor.yy115),
        str.substr(1, str.size() - 2)
    );
}
#line 1552 "sql_grammar.c"
  yymsp[-2].minor.yy115 = yylhsminor.yy115;
        break;
      case 45: /* expression ::= expression TOKEN_EQ expression */
#line 283 "sql_grammar.y"
{
    yylhsminor.yy115 = new ast::BinaryExpression(
        std::unique_ptr<ast::Expression>(yymsp[-2].minor.yy115),
        std::unique_ptr<ast::Expression>(yymsp[0].minor.yy115),
        ast::BinExpressionType::Equal
    );
}
#line 1564 "sql_grammar.c"
  yymsp[-2].minor.yy115 = yylhsminor.yy115;
        break;
      case 46: /* expression ::= expression TOKEN_NEQ expression */
#line 291 "sql_grammar.y"
{
    yylhsminor.yy115 = new ast::BinaryExpression(
        std::unique_ptr<ast::Expression>(yymsp[-2].minor.yy115),
        std::unique_ptr<ast::Expression>(yymsp[0].minor.yy115),
        ast::BinExpressionType::NotEqual
    );
}
#line 1576 "sql_grammar.c"
  yymsp[-2].minor.yy115 = yylhsminor.yy115;
        break;
      case 47: /* expression ::= expression TOKEN_AND expression */
#line 299 "sql_grammar.y"
{
    yylhsminor.yy115 = new ast::BinaryExpression(
        std::unique_ptr<ast::Expression>(yymsp[-2].minor.yy115),
        std::unique_ptr<ast::Expression>(yymsp[0].minor.yy115),
        ast::BinExpressionType::And
    );
}
#line 1588 "sql_grammar.c"
  yymsp[-2].minor.yy115 = yylhsminor.yy115;
        break;
      case 48: /* expression ::= expression TOKEN_OR expression */
#line 307 "sql_grammar.y"
{
    yylhsminor.yy115 = new ast::BinaryExpression(
        std::unique_ptr<ast::Expression>(yymsp[-2].minor.yy115),
        std::unique_ptr<ast::Expression>(yymsp[0].minor.yy115),
        ast::BinExpressionType::Or
    );
}
#line 1600 "sql_grammar.c"
  yymsp[-2].minor.yy115 = yylhsminor.yy115;
        break;
      case 49: /* expression ::= expression TOKEN_DIVIDE expression */
#line 315 "sql_grammar.y"
{
    yylhsminor.yy115 = new ast::BinaryExpression(
        std::unique_ptr<ast::Expression>(yymsp[-2].minor.yy115),
        std::unique_ptr<ast::Expression>(yymsp[0].minor.yy115),
        ast::BinExpressionType::Divide
    );
}
#line 1612 "sql_grammar.c"
  yymsp[-2].minor.yy115 = yylhsminor.yy115;
        break;
      case 50: /* expression ::= TOKEN_COUNT TOKEN_LPAREN expression TOKEN_RPAREN */
#line 323 "sql_grammar.y"
{
    yymsp[-3].minor.yy115 = new ast::UnaryAggregateExpression(
        std::unique_ptr<ast::Expression>(yymsp[-1].minor.yy115),
        ast::UnaryAggregateType::Count
    );
}
#line 1623 "sql_grammar.c"
        break;
      case 51: /* expression ::= TOKEN_MIN TOKEN_LPAREN expression TOKEN_RPAREN */
#line 330 "sql_grammar.y"
{
    yymsp[-3].minor.yy115 = new ast::UnaryAggregateExpression(
        std::unique_ptr<ast::Expression>(yymsp[-1].minor.yy115),
        ast::UnaryAggregateType::Min
    );
}
#line 1633 "sql_grammar.c"
        break;
      case 52: /* expression ::= TOKEN_MAX TOKEN_LPAREN expression TOKEN_RPAREN */
#line 337 "sql_grammar.y"
{
    yymsp[-3].minor.yy115 = new ast::UnaryAggregateExpression(
        std::unique_ptr<ast::Expression>(yymsp[-1].minor.yy115),
        ast::UnaryAggregateType::Max
    );
}
#line 1643 "sql_grammar.c"
        break;
      case 53: /* expression ::= TOKEN_SUM TOKEN_LPAREN expression TOKEN_RPAREN */
#line 344 "sql_grammar.y"
{
    yymsp[-3].minor.yy115 = new ast::UnaryAggregateExpression(
        std::unique_ptr<ast::Expression>(yymsp[-1].minor.yy115),
        ast::UnaryAggregateType::Sum
    );
}
#line 1653 "sql_grammar.c"
        break;
      case 54: /* expression ::= TOKEN_COALESCE TOKEN_LPAREN expression_list TOKEN_RPAREN */
#line 351 "sql_grammar.y"
{
    yymsp[-3].minor.yy115 = new ast::CoalesceExpression(yymsp[-1].minor.yy64);
}
#line 1660 "sql_grammar.c"
        break;
      case 55: /* expression ::= TOKEN_RSUBSTR TOKEN_LPAREN expression TOKEN_COMMA TOKEN_STR TOKEN_RPAREN */
#line 355 "sql_grammar.y"
{
    auto str = std::string(yymsp[-1].minor.yy0.text);

    yymsp[-5].minor.yy115 = new ast::RSubstrExpression(
        std::unique_ptr<ast::Expression>(yymsp[-3].minor.yy115),
        str.substr(1, str.size() - 2)
    );
}
#line 1672 "sql_grammar.c"
        break;
      case 56: /* expression ::= TOKEN_PERCENTILE TOKEN_LPAREN expression TOKEN_COMMA floating_list TOKEN_RPAREN */
#line 364 "sql_grammar.y"
{
    yymsp[-5].minor.yy115 = new ast::PercentileExpression(
        std::unique_ptr<ast::Expression>(yymsp[-3].minor.yy115),
        yymsp[-1].minor.yy49
    );
}
#line 1682 "sql_grammar.c"
        break;
      case 57: /* expression ::= expression TOKEN_IN select_source */
#line 371 "sql_grammar.y"
{
    yylhsminor.yy115 = new ast::InExpression(
        std::unique_ptr<ast::Expression>(yymsp[-2].minor.yy115),
        std::unique_ptr<ast::Node>(yymsp[0].minor.yy77)
    );
}
#line 1692 "sql_grammar.c"
  yymsp[-2].minor.yy115 = yylhsminor.yy115;
        break;
      case 58: /* floating_list ::= TOKEN_FLOATING */
#line 378 "sql_grammar.y"
{
    yylhsminor.yy49 = new std::vector<float>();
    yylhsminor.yy49->push_back(std::strtof(yymsp[0].minor.yy0.text, nullptr));
}
#line 1701 "sql_grammar.c"
  yymsp[0].minor.yy49 = yylhsminor.yy49;
        break;
      case 59: /* floating_list ::= floating_list TOKEN_COMMA TOKEN_FLOATING */
#line 383 "sql_grammar.y"
{
    yylhsminor.yy49 = yymsp[-2].minor.yy49;
    yylhsminor.yy49->push_back(std::strtof(yymsp[0].minor.yy0.text, nullptr));
}
#line 1710 "sql_grammar.c"
  yymsp[-2].minor.yy49 = yylhsminor.yy49;
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 388 "sql_grammar.y"

    const char* token_text = TOKEN.text;
    fprintf(stderr, "Syntax error at line near token: '%s'\n", token_text);
    pCtx->has_error = 1;
#line 1778 "sql_grammar.c"
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
        if( yypParser->yytos>=yypParser->yystackEnd ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
