#define TOKEN_SELECT                     1
#define TOKEN_COUNT                      2
#define TOKEN_FROM                       3
#define TOKEN_IDENTIFIER                 4
#define TOKEN_SEMICOLON                  5
#define TOKEN_EOF                        6
#define TOKEN_AS                         7
#define TOKEN_IN                         8
#define TOKEN_COALESCE                   9
#define TOKEN_COMMA                     10
#define TOKEN_STAR                      11
#define TOKEN_WHERE                     12
#define TOKEN_LIMIT                     13
#define TOKEN_INTEGER                   14
#define TOKEN_FLOATING                  15
#define TOKEN_PATH                      16
#define TOKEN_STR                       17
#define TOKEN_RSUBSTR                   18
#define TOKEN_LPAREN                    19
#define TOKEN_RPAREN                    20
#define TOKEN_AT                        21
#define TOKEN_GROUP_BY                  22
#define TOKEN_ORDER_BY                  23
#define TOKEN_TRUE                      24
#define TOKEN_FALSE                     25
#define TOKEN_DESC                      26
#define TOKEN_ASC                       27
#define TOKEN_NULL                      28
#define TOKEN_DOLLAR                    29
#define TOKEN_UNION_ALL                 30
#define TOKEN_MIN                       31
#define TOKEN_MAX                       32
#define TOKEN_SUM                       33
#define TOKEN_PERCENTILE                34
#define TOKEN_PLUS                      35
#define TOKEN_OR                        36
#define TOKEN_AND                       37
#define TOKEN_DIVIDE                    38
#define TOKEN_EQ                        39
#define TOKEN_NEQ                       40
#define TOKEN_LIKE                      41
#define TOKEN_MATERIALIZE               42
#define TOKEN_STRING                    43
#define TOKEN_INT                       44
#define TOKEN_FLOAT                     45
#define TOKEN_BOOL                      46
#define TOKEN_EXCLAMATION               47
#define TOKEN_TIMESTAMP                 48
